### ISSUE TITLE
Create a basic library and demo in Javascript

### ISSUE THREAD

**Issue by EggPool** [EggPool/BismuthAPI#2]
Goal is to be simple and easy to understand, cross platform.

See specs and python/php directories for what is expected to port.

Minimal use of third party libraries (none should be needed)

**Comment by EggPool** [comment]
Successfully handled by @gabidi, thanks!

**Comment by gabidi** [comment]
:+1

**Comment by EggPool** [comment]
Done by @gabidi , thanks!
